-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE PACIENTE (
ID_PACIENTE INTEGER PRIMARY KEY,
NOME VARCHAR(100),
CPF CHAR(11),
DT_NASC DATE,
SEXO CHAR(1),
TP_SANGUINEO VARCHAR(3),
EMAIL VARCHAR(100),
TELEFONE VARCHAR(30),
ENDERECO VARCHAR(100)
)

CREATE TABLE MEDICO (
ID_MEDICO INTEGER PRIMARY KEY,
NOME VARCHAR(100),
DT_NASC DATE,
SEXO CHAR(1),
ENDERECO VARCHAR(100),
EMAIL VARCHAR(100),
TELEFONE VARCHAR(30),
CRM VARCHAR(10),
ESPECIALIDADE VARCHAR(100)
)

CREATE TABLE CONSULTA (
ID_CONSULTA INTEGER PRIMARY KEY,
HR_CONSULTA TIME,
DT_CONSULTA DATE,
LOCALIZACAO VARCHAR(100),
EXAME VARCHAR(100),
PRESCRICAO VARCHAR(100),
DIAGNOSTICO VARCHAR(100),
ID_MEDICO INTEGER,
ID_PACIENTE INTEGER,
FOREIGN KEY(ID_MEDICO) REFERENCES MEDICO (ID_MEDICO),
FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTE (ID_PACIENTE)
)

