-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE CLIENTE (
ID_CLIENTE INTEGER PRIMARY KEY,
NOME VARCHAR(100),
DT_NASC DATE,
TELEFONE VARCHAR(30),
PERFIL_FINANCEIRO VARCHAR(20),
LOGRADOURO VARCHAR(60),
CIDADE VARCHAR(60),
UF CHAR(2)
)

CREATE TABLE AGENCIA (
ID_AGENCIA INTEGER PRIMARY KEY,
NOME VARCHAR(100),
CNPJ CHAR(14),
GERENTE VARCHAR(100),
LOGRADOURO VARCHAR(60),
CIDADE VARCHAR(60),
UF CHAR(2)
)

CREATE TABLE CONTA_CORRENTE (
ID_CONTA INTEGER PRIMARY KEY,
SENHA VARCHAR(20),
DT_CRIACAO DATE,
VLR_LIMITE NUMERIC(8,2),
VLR_SALDO NUMERIC(8,2),
ID_CLIENTE INTEGER,
ID_AGENCIA INTEGER,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
FOREIGN KEY(ID_AGENCIA) REFERENCES AGENCIA (ID_AGENCIA)
)

CREATE TABLE EMPRESTIMO (
ID_EMPRESTIMO INTEGER PRIMARY KEY,
QTD_PARCELA INTEGER,
VLR_EMPRESTIMO NUMERIC(8,2),
PERCENTUAL_JUROS NUMERIC(5,2),
STATUS_EMPRESTIMO VARCHAR(60),
DT_EFETIVACAO DATE,
DT_ENCERRAMENTO DATE,
ID_CONTA INTEGER,
FOREIGN KEY(ID_CONTA) REFERENCES CONTA_CORRENTE (ID_CONTA)
)

