-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.


CREATE TABLE DEPARTAMENTO (
ID_DEPARTAMENTO INTEGER PRIMARY KEY,
NOME_DEPARTAMENTO VARCHAR(100),
SIGLA VARCHAR(20),
RAMAL VARCHAR(20),
RESPONSAVEL VARCHAR(100),
LOCALIZACAO VARCHAR(100),
ORCAMENTO NUMERIC(8,2)
);

CREATE TABLE FUNCIONARIO (
ID_FUNCIONARIO INTEGER PRIMARY KEY,
NOME VARCHAR(100),
CPF CHAR(11),
DT_NASC DATE,
SEXO CHAR(1),
ENDERECO VARCHAR(100),
ESTADO_CIVIL VARCHAR(20),
EMAIL VARCHAR(100),
TELEFONE VARCHAR(20),
NUM_MATRICULA INTEGER,
DT_ADMISSAO DATE,
SALARIO NUMERIC(7,2),
CARGO VARCHAR(60),
ID_DEPARTAMENTO INTEGER,
FOREIGN KEY(ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
);



